import Link from 'next/link';
import type {ReactNode} from 'react';
import {alliances} from '@/data/kingdom';
import {TransferLink, TransferNote} from '@/components/transfer-link';
function ServiceLink({href,children}:{href:string;children:ReactNode}){return href==='/join'?<TransferLink>{children}</TransferLink>:<Link href={href}>{children}</Link>}
const links=[['Player Profile','Your heroes, Governor Gear, charms, and troop tiers','/members/profile'],['KvK Prep','Speedup days and minister availability','/members/prep'],['KvK Battle','Your battle window, 10:00–22:00 UTC','/members/availability'],['Upgrade Tools','Gear, charms, and construction planners','/tools'],['Game Guides','Search trusted game and kingdom guidance','/guides'],['Kingdom Timeline','Kingdom 2312 unlocks and progression','/timeline']];
export default function Home(){return <div className="reference-home">
<section className="ref-hero"><div className="wrap"><p className="ref-label">KINGSHOT · KINGDOM 2312</p><h1>WELCOME<br/>TO KINGDOM<br/>2312.</h1><p className="ref-intro">Six alliances. One multilingual kingdom. Find your next event, prepare your upgrades, update your profile, or start your transfer journey.</p><p className="ref-motto">Forged in KvK. Built to win.</p><div className="button-row"><TransferLink className="button">Apply for a transfer</TransferLink><Link className="button secondary" href="/tools">View member tools</Link></div><TransferNote/></div></section>
<section className="ref-features" aria-label="Community services">{[['01','Transfers','Find your alliance and share your player information.','/join'],['02','Member forms','Keep your player profile and KvK availability up to date.','/members'],['03','Calculators','Plan your Governor Gear, charm, and construction upgrades.','/tools']].map(([n,t,d,url])=><ServiceLink href={url} key={n}><span className="ref-label">{n}</span><h2>{t}</h2><p>{d}</p></ServiceLink>)}</section>
<section className="wrap ref-links" id="member-links"><div><p className="ref-label">MEMBER LINKS</p><h2>WHAT DO<br/>YOU NEED?</h2><p>Your kingdom essentials, all in one place.</p></div><div>{links.map(([t,d,url],i)=><Link className="ref-link-row" href={url} key={t}><span className="ref-label">0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div><span className="ref-link-mark" aria-hidden="true">+</span></Link>)}</div></section>
<section className="ref-story" id="kingdom-story"><div className="ref-gallery"><img src="/art/fortress.webp" alt="Original concept art of an illuminated fortress in a mountain valley" loading="lazy"/><Link className="button secondary" href="/gallery">View gallery</Link><p>Original Kingdom 2312 concept art</p></div><div className="ref-how"><p className="ref-label">ABOUT THE KINGDOM</p><h2>HOW 2312<br/>WORKS</h2><p>404, 401, FXF, BLO, OMG, and GLX. Six teams coordinating events, preparing for KvK, and standing together.</p><div className="ref-principles">{[['I','Alliance event times','Choose an alliance whose UTC schedule works for you. Confirm the latest times with your officers.'],['II','Reviewed transfers','Leadership reviews your account, availability, and KvK participation before confirming a place.'],['III','One home for member tasks','Check events, update your profile, and plan the upgrades that matter to your team.']].map(([n,t,d])=><article key={n}><span className="ref-label">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div><Link className="text-link" href="/about">Read about Kingdom 2312</Link></div></section>
<section className="wrap ref-alliances" id="alliance-schedules"><p className="ref-label">ALLIANCE SCHEDULES</p><h2>SIX ALLIANCES.<br/>ONE KINGDOM.</h2><div className="three-grid">{alliances.map(a=><Link className="ref-alliance" href={`/alliances/${a.slug}`} key={a.tag}><span className="ref-alliance-tag">{a.tag}</span><div><h3>{a.name}</h3><p>Bear Trap 1: {a.bearTrap1} UTC</p><p>Bear Trap 2: {a.bearTrap2} UTC</p><p>R5: {a.leader||'To be announced'}</p></div></Link>)}</div></section>
<section className="ref-transfer" id="transfer"><p className="ref-label">KINGDOM TRANSFERS</p><h2>YOUR NEXT CHAPTER.<br/>KINGDOM 2312.</h2><p>Never outnumbered, never outworked.</p><TransferLink className="button">Open the transfer form</TransferLink><TransferNote/></section>
</div>}
